language: ruby
rvm:
- 2.6.3
before_install:
- openssl aes-256-cbc -K $encrypted_c0f20a007d18_key -iv $encrypted_c0f20a007d18_iv -in deploy_rsa.enc -out deploy_rsa -d
- export TZ=America/Central
before_script:
- chmod +x ./scripts/cibuild.sh
- echo 'America/Central' | sudo tee /etc/timezone
- sudo dpkg-reconfigure --frontend noninteractive tzdata
before_deploy:
- openssl aes-256-cbc -K $encrypted_c0f20a007d18_key -iv $encrypted_c0f20a007d18_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: "./scripts/cibuild.sh"
branches:
  only:
  - master
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production
  - secure: xlWEYbXeqytVg35snT0Ublt4u2jBnEtwuNDi4X1Q6Ylg07Jyaj/XxUzCB8XkxiMg23sR6DRh20PHpU709mF02zXhiewE9cw6xqB7aPmEMzD+s0OaUaXx+Ty2+0wXUcF5p/lsYEgfRsKXFHUYmi5XX4ReYuRornffPbiwtZqApcUuqlGWiPb2LhlPvt9hKmvOpF7JDYqsQyuzU+SczF+MEMqX1pBPtYHEAR29hnRJ0GoTbHo9XQD0bi4RgKGIgID7qij0I0aD44+/oeQeq3vJ2CqWSlK15cCmw/rWSjjZ1tkyM3zQzFvcYatXkQ7y87RrAJzQklW++tVBONo8WUp8fJKP82J0rgF5OZHOktfk9IjkTjSwXpG85ss9Jl/Q4VKfrLHHIWel23qVmN04cq0LKRYrLfbMVeZ4W1O5lqjnHpiQL2iGh3pKFIdWWXaAkkvModM2ftpTorLdcm8h0I0M/D+sUB3UwSX9xf0r2dgJQCJ27sWl0qyi8rm+tWToNnzwBodSlbRMarSmuOo1kqQpf8rld4Jty2sQ7qhAfKHRwZoGNYlEDuB/hkrSJdtodXcd1bssJZeoU0Y5sCcJv1SBNonPmp3ThpeudbWiw4HhFgyL4+kfQCHwQLZ+pSbgNmCdJkEOPL88yE52M3HgbUipiS/RTD8MJDWy+Lne67ZVhoA=
  - secure: eAQQ1n+UoxXxvztKK51ZU6CPY1kKcsMD0K5MFiXXI889BY7YngS+TXr8FmQZ8Ga0fgt9TnJnBcebnhDwkQwBs/MVSnzk36AI8BYSUBkDz6KlJazA7k2eqKuPkL20ub+/05NUSWOhXwDsJF9zPfUkxxSV9P8FRuWVe72PJ16//vy7qCluLmy0tEypwD2HtiFa+y7xuIBuFqSQa7ZrpCVtdMyrqW+GyyK9fJ96LvlBDanReXijomDtYt6DRVddT9dIHWe8ait01UHol3XryukVZOkRITAWfPs313K4iLmamfs5fdt0d/DOHwPzSirf9EO9ghYAxf6HGSADImjcbpF/LyMwYPDcWEiPQPYoA6cVaXHh4nfcjap3bJFdR/DF64eh9jLcB1LyxunpoPWRxbYDF3xPUSWus2RLdF33lLfPrWHtWVw2rE6Cle60ZliMMRo2+aT3X3TmghR31hm/SP3VjIZtbBW09d6SI+5saSpVbtHs+FeQ1wGIkeTQDRShwXjnXK785o15xTVapk6PS0V6vRfqZcUgeqPlzAwKYMavBePaUAGR2De9cBIA5f/Br78fQDm/KZ0DPKPGAnY94Q/r5SZ/Y9iIf5zjxou/JV7ojLYkE8Yv6tgwcWLU6Dodz1AtZPlMwtDjHVBglU/SU6errlL56TH0OGe/34ih9OhQY3g=
  - secure: sgMHxK0UyQXweKRXGvWu0fxZhoRQDx/a+EcDdWidafvO1/vgnPOPrYaMEKrk+iZjN5B9AAvlo7oYxmCsU+BgKGQSugWSOJaf7zwZLxDK++qvvR3tzdlRRdMRZTdBhvFCL2Yf72UiK/TYt/fJTGQZaPFUxLGHLbf15klA0wnK/5IHtJMS5zxGcEjeEi8dQdnxkqsgKqfFk5zzMfr+RhG8n2xI5+xlhg3dH7ExhNw2EuvzZhrbxMPE5Jd4wLquu5wZ2+BUN/MaZDP587AGBbQ+q2JMFstTMxWd309EQfgMy/PqvdwgLc+V/tnBbdifMnv0of5HLfSievuV0D5rNmDBXs1eCcoBom9HPUkktCxV/xvJ+tUpXKXR5HSBDeJG7ijz9znfPH5wE4x8p3CkeHqS3CB5yf/ryxsy4l0YtuhlMRLfuDFOD7yWPOM4BsSMSMlqzo8STxR5/+O5TgbzLBj+A13NPwSyBpmVT6jy4nRzeWyfzd2qBUKD8R0m2jn0u1uHxOOpLbjwi/GEkznbuI3nCKJAEW//40jEwtab0THhQoV+g28WA2IkTVWY25/FHSwUNkNbQmwWDYEbxg7K5cpWv20Kgax3ONnDYndNSKafV/je8RACJRHYJ26LdrqYSpRMNNAaBpr9nGtjyHPkFqZSSjxBgasfiw9sihtqgJsXu/0=
cache: bundler
notifications:
  email: true
