language: ruby
rvm:
  - 2.6.3

before_install:
  - export TZ=America/Central

before_script:
  - chmod +x ./scripts/cibuild.sh # or do this locally and commit
  - echo 'America/Central' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=production

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: true