name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: rsync deployments
      uses: contention/rsync-deployments@v1.0.0
      env: 
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
      with: 
        args: "-avz _site/ root@alitebyte.com:/var/www/alitebyte.com/html/"
